### ISSUE TITLE
Assigning ISteamUser.GetPlayerSummaries(ulong) to a GetPlayerSummariesResponse errors

### ISSUE THREAD

**Issue by marchcain** [armageddonapps/QueryMaster#1]
`public static string getNameFromID(ulong ID)`
        `{`
            `GetPlayerSummariesResponse resp = ISteamUser.GetPlayerSummaries(ID);`
            `return resp.ParsedResponse.Players[0].PersonaName;`
        `}`
The 3rd line, no matter what I do, will error with "An object reference is required for the non-static field, method, or property 'ISteamUser.GetPlayerSummaries(param ulong[])". I've also tried making the method non-static, neither work.

**Comment by ElusiveAvenger** [comment]
GetPlayerSummaries is not static method. The call must be made through an instance of the SteamQuery class.
Try
```
public static string getNameFromID(ulong ID)
{
    var steamQuery = new SteamQuery();
    GetPlayerSummariesResponse resp = steamQuery.ISteamUser.GetPlayerSummaries(ID);
    return resp.ParsedResponse.Players[0].PersonaName;
}
```

**Comment by ElusiveAvenger** [comment]
> `public static string getNameFromID(ulong ID)`
> `{`
> `GetPlayerSummariesResponse resp = ISteamUser.GetPlayerSummaries(ID);`
> `return resp.ParsedResponse.Players[0].PersonaName;`
> `}`
> The 3rd line, no matter what I do, will error with "An object reference is required for the non-static field, method, or property 'ISteamUser.GetPlayerSummaries(param ulong[])". I've also tried making the method non-static, neither work.

GetPlayerSummaries is not static method. The call must be made through an instance of the SteamQuery class.
Try
```
public static string getNameFromID(ulong ID)
{
    var steamQuery = new SteamQuery("your_api_key");
    GetPlayerSummariesResponse resp = steamQuery.ISteamUser.GetPlayerSummaries(ID);
    return resp.ParsedResponse.Players[0].PersonaName;
}
```
